apiVersion: v1
kind: Pod
metadata:
  name:pod_ex
  labels: 
    app: hello_pod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - name: ng_port
      port: 80
  - name: watcher
    image: afakharany/watcher
  
