apiVersion: v1
kind: Pod
metadata:
  name: podex
  labels: 
    app: hello_pod
spec:
  containers:
  - name: webserver
    image: nginx
    ports:
      containerPort: 80
  - name: webwatcher
    image: afakharany/watcher
